### ISSUE TITLE
Issue-not issue : MQTT config

### ISSUE THREAD

**Issue by Tokn59** [rhannink/M5Stack-HA-Alarm-panel#1]
Hi, thanks for sharing this great project with us ! I am in the process of implementing this. The m5stack has been flashed but for the time being I use no RFID add on, just the buttons.

My config in Arduno for MQTT : 

 const char* mqtt_clientId = "M5stack-alarm";
const char* mqtt_state_topic = "home/alarm";
const char* mqtt_command_topic = "home/alarm/set";
const char* mqtt_state_full = "armed_away";
const char* mqtt_state_part = "armed_home";
const char* mqtt_state_off = "disarmed";
const char* mqtt_state_pending = "pending";
const char* mqtt_command_full = "ARM_AWAY";
const char* mqtt_command_part = "ARM_HOME";
const char* mqtt_command_off = "DISARM";
const char* display_state_full ="Fully Armed";
const char* display_state_part ="Partially Armed";
const char* display_state_off ="Switched Off";
const char* display_state_pending ="Pending";
const char* display_present_card = "Please present Card!";
const char* button_a_text = "Off";
const char* button_b_text = "Home";
const char* button_c_text = "Away";

My config of the mqtt entry in configuration.yaml  : 

 alarm_control_panel:
  - platform: mqtt
    state_topic: "home/alarm"
    command_topic: "home/alarm/set"

and finally my config in the Lovelace card : 

entity: alarm_control_panel.mqtt_alarm
name: M5Stack Alarm Panel
states:
  - arm_home
  - arm_away
type: alarm-panel

Is this a correct configuration ? 

I do  not see any changes when pressing the M5Stack buttons ...

Thanks for your help !

Tony

**Comment by andyacep** [comment]
yep it does that without the rfid board
you would need to comment out the line
    // Initialize RFID reader
    // mfrc522.PCD_Init();             // Init MFRC522
